### ISSUE TITLE
Replace Healthchecks with Gatus external-endpoints

### ISSUE THREAD

**Issue by claha** [claha/smart-home#417]
One service less, that was also 100% manual setup

**Comment by claha** [comment]
```yaml
external-endpoints:
  - name: test
    group: health
    token: "gatus"
    alerts:
      - type: telegram
```

Works well, currently there is no "expect this to be called every hour wiht some grace", but my backup scripts should be able to call success/fail on each instead
